name: Reusable workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
jobs:
  example-job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Test
      run: echo Hello ${{ inputs.username }} From this step!
